# Generated by Django 2.0.3 on 2018-04-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, unique=True)),
                ('msatoshi', models.BigIntegerField()),
                ('quoted_currency', models.CharField(max_length=4, null=True, verbose_name='currency')),
                ('quoted_amount', models.DecimalField(decimal_places=3, max_digits=20, null=True, verbose_name='amount')),
                ('rhash', models.CharField(max_length=300, unique=True)),
                ('payreq', models.CharField(max_length=1000)),
                ('status', models.CharField(default='unpaid', max_length=128)),
                ('pay_index', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=640)),
                ('metadata', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
